In [1]:
import numpy as np
import pandas as pd

In [46]:
date = pd.read_csv("orders.csv")
time = pd.read_csv("messages.csv")

In [3]:
date

           date  product_id  city_id  orders
0    2019-12-10        5628       25       3
1    2018-08-15        3646       14     157
2    2018-10-23        1859       25       1
3    2019-08-17        7292       25       1
4    2019-01-06        4344       25       3
..          ...         ...      ...     ...
995  2018-10-08         255       13       1
996  2018-12-06        5521        7       1
997  2019-05-07         487       26      14
998  2019-03-03        1503       21       2
999  2019-10-15        6371        7      22

[1000 rows x 4 columns]

In [4]:
time

                    date                                                msg
0    2013-12-15 00:50:00                           ищу на сегодня мужика 37
1    2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2    2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3    2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4    2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше
..                   ...                                                ...
995  2012-03-16 00:50:00     ПАРЕНЬ СДЕЛАЕТ  МАССАЖ ЖЕНЩИНАМ -066-877-32-44
996  2014-01-23 23:14:00            сельский п 23 ищу девушку для отношений
997  2012-10-15 23:37:00  Д+Д ДЛЯ серьезных отношений. Мой номер 093-156...
998  2012-06-21 23:34:00  7 ДНЕПР М.34 ПОЗ.С Д/Ж ДЛЯ ВСТРЕЧ.Т.098 809 15 14
999  2014-06-19 23:25:00          Парень поласкает девушке...  т.0662035584

[1000 rows x 2 columns]

In [5]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [6]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [7]:
date["date"] = pd.to_datetime(date["date"])

In [8]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [9]:
date.sample(5)

          date  product_id  city_id  orders
437 2019-08-04        2830       14      21
691 2019-06-22        1917        0       2
182 2019-05-26        1135       28       1
411 2019-12-11        3179       22      16
144 2019-10-14        5778       24     108

In [10]:
# extract the year

date["date_year"] = date["date"].dt.year

In [11]:
date

          date  product_id  city_id  orders  date_year
0   2019-12-10        5628       25       3       2019
1   2018-08-15        3646       14     157       2018
2   2018-10-23        1859       25       1       2018
3   2019-08-17        7292       25       1       2019
4   2019-01-06        4344       25       3       2019
..         ...         ...      ...     ...        ...
995 2018-10-08         255       13       1       2018
996 2018-12-06        5521        7       1       2018
997 2019-05-07         487       26      14       2019
998 2019-03-03        1503       21       2       2019
999 2019-10-15        6371        7      22       2019

[1000 rows x 5 columns]

In [12]:
# extact the month date

date["date_month"] = date["date"].dt.month

In [13]:
date

          date  product_id  city_id  orders  date_year  date_month
0   2019-12-10        5628       25       3       2019          12
1   2018-08-15        3646       14     157       2018           8
2   2018-10-23        1859       25       1       2018          10
3   2019-08-17        7292       25       1       2019           8
4   2019-01-06        4344       25       3       2019           1
..         ...         ...      ...     ...        ...         ...
995 2018-10-08         255       13       1       2018          10
996 2018-12-06        5521        7       1       2018          12
997 2019-05-07         487       26      14       2019           5
998 2019-03-03        1503       21       2       2019           3
999 2019-10-15        6371        7      22       2019          10

[1000 rows x 6 columns]

In [16]:

# extract the month name
date["date_month_name"] = date["date"].dt.month_name()

In [17]:
date

,date,product_id,city_id,orders,date_year,date_month,date_month_name
0,2019-12-10,5628,25,3,2019,12,December
1,2018-08-15,3646,14,157,2018,8,August
2,2018-10-23,1859,25,1,2018,10,October
3,2019-08-17,7292,25,1,2019,8,August
4,2019-01-06,4344,25,3,2019,1,January
...,...,...,...,...,...,...,...
995,2018-10-08,255,13,1,2018,10,October
996,2018-12-06,5521,7,1,2018,12,December
997,2019-05-07,487,26,14,2019,5,May
998,2019-03-03,1503,21,2,2019,3,March
999,2019-10-15,6371,7,22,2019,10,October

In [18]:
# extract the day
date["date_day"] = date["date"].dt.day

In [19]:
date

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day
0,2019-12-10,5628,25,3,2019,12,December,10
1,2018-08-15,3646,14,157,2018,8,August,15
2,2018-10-23,1859,25,1,2018,10,October,23
3,2019-08-17,7292,25,1,2019,8,August,17
4,2019-01-06,4344,25,3,2019,1,January,6
...,...,...,...,...,...,...,...,...
995,2018-10-08,255,13,1,2018,10,October,8
996,2018-12-06,5521,7,1,2018,12,December,6
997,2019-05-07,487,26,14,2019,5,May,7
998,2019-03-03,1503,21,2,2019,3,March,3
999,2019-10-15,6371,7,22,2019,10,October,15

In [20]:
# week mein konsa din ha

date["date_week"] = date["date"].dt.dayofweek

In [21]:
date

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_week
0,2019-12-10,5628,25,3,2019,12,December,10,1
1,2018-08-15,3646,14,157,2018,8,August,15,2
2,2018-10-23,1859,25,1,2018,10,October,23,1
3,2019-08-17,7292,25,1,2019,8,August,17,5
4,2019-01-06,4344,25,3,2019,1,January,6,6
...,...,...,...,...,...,...,...,...,...
995,2018-10-08,255,13,1,2018,10,October,8,0
996,2018-12-06,5521,7,1,2018,12,December,6,3
997,2019-05-07,487,26,14,2019,5,May,7,1
998,2019-03-03,1503,21,2,2019,3,March,3,6
999,2019-10-15,6371,7,22,2019,10,October,15,1

In [22]:
date["date_dow_name"] = date["date"].dt.day_name()

In [24]:
date.drop(columns=["product_id","city_id","orders"]).head()

,date,date_year,date_month,date_month_name,date_day,date_week,date_dow_name
0,2019-12-10,2019,12,December,10,1,Tuesday
1,2018-08-15,2018,8,August,15,2,Wednesday
2,2018-10-23,2018,10,October,23,1,Tuesday
3,2019-08-17,2019,8,August,17,5,Saturday
4,2019-01-06,2019,1,January,6,6,Sunday

In [25]:
# is weekend?

date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday', 'Saturday']), 1,0)

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month,date_month_name,date_day,date_week,date_dow_name,date_is_weekend
0,2019-12-10,2019,12,December,10,1,Tuesday,0
1,2018-08-15,2018,8,August,15,2,Wednesday,0
2,2018-10-23,2018,10,October,23,1,Tuesday,0
3,2019-08-17,2019,8,August,17,5,Saturday,1
4,2019-01-06,2019,1,January,6,6,Sunday,1

In [27]:
date['quarter'] = date['date'].dt.quarter # extract the quarter 

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month,date_month_name,date_day,date_week,date_dow_name,date_is_weekend,quarter
0,2019-12-10,2019,12,December,10,1,Tuesday,0,4
1,2018-08-15,2018,8,August,15,2,Wednesday,0,3
2,2018-10-23,2018,10,October,23,1,Tuesday,0,4
3,2019-08-17,2019,8,August,17,5,Saturday,1,3
4,2019-01-06,2019,1,January,6,6,Sunday,1,1

In [28]:
date['semester'] = np.where(date['quarter'].isin([1,2]), 1, 2) # extracf the semester 

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month,date_month_name,date_day,date_week,date_dow_name,date_is_weekend,quarter,semester
0,2019-12-10,2019,12,December,10,1,Tuesday,0,4,2
1,2018-08-15,2018,8,August,15,2,Wednesday,0,3,2
2,2018-10-23,2018,10,October,23,1,Tuesday,0,4,2
3,2019-08-17,2019,8,August,17,5,Saturday,1,3,2
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1

In [34]:
# Extract Time elapsed between dates
import datetime

today = datetime.datetime.today()

In [33]:
today

datetime.datetime(2026, 7, 31, 16, 55, 54, 719158)

In [35]:
today - date["date"]

0     2425 days 16:56:01.066769
1     2907 days 16:56:01.066769
2     2838 days 16:56:01.066769
3     2540 days 16:56:01.066769
4     2763 days 16:56:01.066769
                 ...
995   2853 days 16:56:01.066769
996   2794 days 16:56:01.066769
997   2642 days 16:56:01.066769
998   2707 days 16:56:01.066769
999   2481 days 16:56:01.066769
Name: date, Length: 1000, dtype: timedelta64[ns]

In [36]:
(today - date['date']).dt.days

0      2425
1      2907
2      2838
3      2540
4      2763
       ...
995    2853
996    2794
997    2642
998    2707
999    2481
Name: date, Length: 1000, dtype: int64

In [38]:
# Months passed

np.round((today -date['date']) / np.timedelta64(1, 'm'),0)

0      3493016.0
1      4187096.0
2      4087736.0
3      3658616.0
4      3979736.0
         ...
995    4109336.0
996    4024376.0
997    3805496.0
998    3899096.0
999    3573656.0
Name: date, Length: 1000, dtype: float64

In [39]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [48]:
time["date"] = pd.to_datetime(time["date"])

In [49]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [52]:
time["hour"] = time["date"].dt.hour
time["min"] = time["date"].dt.minute
time["sec"] = time["date"].dt.second

In [53]:
time

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0
...,...,...,...,...,...
995,2012-03-16 00:50:00,ПАРЕНЬ СДЕЛАЕТ МАССАЖ ЖЕНЩИНАМ -066-877-32-44,0,50,0
996,2014-01-23 23:14:00,сельский п 23 ищу девушку для отношений,23,14,0
997,2012-10-15 23:37:00,Д+Д ДЛЯ серьезных отношений. Мой номер 093-156...,23,37,0
998,2012-06-21 23:34:00,7 ДНЕПР М.34 ПОЗ.С Д/Ж ДЛЯ ВСТРЕЧ.Т.098 809 15 14,23,34,0
999,2014-06-19 23:25:00,Парень поласкает девушке... т.0662035584,23,25,0

In [54]:
time["time"] = time["date"].dt.time

In [55]:
time

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00
...,...,...,...,...,...,...
995,2012-03-16 00:50:00,ПАРЕНЬ СДЕЛАЕТ МАССАЖ ЖЕНЩИНАМ -066-877-32-44,0,50,0,00:50:00
996,2014-01-23 23:14:00,сельский п 23 ищу девушку для отношений,23,14,0,23:14:00
997,2012-10-15 23:37:00,Д+Д ДЛЯ серьезных отношений. Мой номер 093-156...,23,37,0,23:37:00
998,2012-06-21 23:34:00,7 ДНЕПР М.34 ПОЗ.С Д/Ж ДЛЯ ВСТРЕЧ.Т.098 809 15 14,23,34,0,23:34:00
999,2014-06-19 23:25:00,Парень поласкает девушке... т.0662035584,23,25,0,23:25:00

In [56]:
# Time difference

today - time["date"]

0     4611 days 16:06:01.066769
1     4475 days 17:16:01.066769
2     4961 days 16:35:01.066769
3     4263 days 16:25:01.066769
4     4660 days 17:45:01.066769
                 ...
995   5250 days 16:06:01.066769
996   4571 days 17:42:01.066769
997   5036 days 17:19:01.066769
998   5152 days 17:22:01.066769
999   4424 days 17:31:01.066769
Name: date, Length: 1000, dtype: timedelta64[ns]

In [57]:
# in seconds

(today - time['date'])/np.timedelta64(1,'s') # s= seconds

0      3.984484e+08
1      3.867022e+08
2      4.286901e+08
3      3.683823e+08
4      4.026879e+08
           ...
995    4.536580e+08
996    3.949981e+08
997    4.351727e+08
998    4.451953e+08
999    3.822967e+08
Name: date, Length: 1000, dtype: float64

In [58]:
# in minutes

(today - time['date'])/np.timedelta64(1,'m') # m = minutes  or big M is months

0      6.640806e+06
1      6.445036e+06
2      7.144835e+06
3      6.139705e+06
4      6.711465e+06
           ...
995    7.560966e+06
996    6.583302e+06
997    7.252879e+06
998    7.419922e+06
999    6.371611e+06
Name: date, Length: 1000, dtype: float64

In [60]:
# in hours

(today - time["date"])/np.timedelta64(1,"h") # time difference today or our datset in tersm of hours

0      110680.100296
1      107417.266963
2      119080.583630
3      102328.416963
4      111857.750296
           ...
995    126016.100296
996    109721.700296
997    120881.316963
998    123665.366963
999    106193.516963
Name: date, Length: 1000, dtype: float64